### ISSUE TITLE
404

### ISSUE THREAD

**Issue by mfirry** [Nycto/Hasher#10]
`http://maven.spikemark.net/roundeights` gives 404

**Comment by Nycto** [comment]
The directories have read permissions locked down, so you can't browse. But the files themselves are available. For example:

http://maven.spikemark.net/roundeights/com/roundeights/hasher_2.11/1.0.0/hasher_2.11.pom

I've been meaning to make the directories readable for a while, but just haven't done it yet. I've closed previous tickets, but I suppose I need a reminder to do this, so I'm leaving this one open

**Comment by mfirry** [comment]
Hmmm... this is not what sbt looks for though.

I added
```
libraryDependencies ++= Seq(
  "com.roundeights" %% "hasher" % "1.0.0"
)
```


I get
```[warn]   http://maven.spikemark.net/roundeights/com/roundeights/hasher_2.11/1.0.0/hasher_2.11-1.0.0.pom```

**Comment by Nycto** [comment]
That URL works for me. Here it is being loaded through a proxy:

http://anonymouse.org/cgi-bin/anon-www.cgi/http://maven.spikemark.net/roundeights/com/roundeights/hasher_2.11/1.0.0/hasher_2.11-1.0.0.pom

Is there perhaps a firewall between you and it?

**Comment by mfirry** [comment]
It works now. That's weird. No, no proxy. Thanks so much!

**Comment by arobertn** [comment]
This actually relates to the issue I was going to report.  Is there any chance this can be hosted at a mature, well-known maven repo?  We don't want to have to end up embedding the dependency into our project at some point down the road.

**Comment by Nycto** [comment]
For unrelated reasons, I would rather tweak the existing repo than switch. Is there something specific you need addressed?

**Comment by arobertn** [comment]
Just the reasoning I gave, vague, unspecific, and non-watertight though it might be. :-)  Would like to feel the odds are good the repo will still be there 5 years down the road while our app is still shipping.  Not that there aren't other factors weighing into library selection (probability of maintained code, tradeoffs of direct embedding vs repo dependency, etc.), but for better or for worse, this is how one person is looking at it!

**Comment by danslapman** [comment]
It don't work for me too. Why don't just publish jar to jCenter?

**Comment by cm-wada-yusuke** [comment]
Just now, internal server error occurred...

**Comment by Nycto** [comment]
Cloudant is apparently down, causing the error: https://twitter.com/CloudantStatus

**Comment by danslapman** [comment]
@Nycto I see there were similar problems in the past, why You just don't switch to another repo?

**Comment by danellis** [comment]
+1 for switching. 500 error is breaking builds. Is there any reason this can't be on Maven Central?

**Comment by danslapman** [comment]
Now. Again :(

**Comment by Nycto** [comment]
Seems to be working for me:
http://anonymouse.org/cgi-bin/anon-www.cgi/http://maven.spikemark.net/roundeights/com/roundeights/hasher_2.11/1.0.0/hasher_2.11.pom

**Comment by Taig** [comment]
You might as well use it via JitPack: https://jitpack.io/#Nycto/Hasher/v1.2.0

**Comment by Nycto** [comment]
Alright. Relent. Despite my distaste for using Nexus, I cut a ticket to Sonatype to start publish to maven central. I'm resolving this ticket.
