### ISSUE TITLE
com.roundeights#hasher_2.11;1.2.0: not found

### ISSUE THREAD

**Issue by thewhisperinyourears** [Nycto/Hasher#17]
I am trying to install a script but throws this error.
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.roundeights#hasher_2.11;1.2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by darkfrog26** [comment]
I'm seeing this issue as well.  It would also be really beneficial if you started pushing to Maven Central instead of your own repo.

**Comment by darkfrog26** [comment]
I figured since this has been waiting a month for updates I'd do something about it myself.  I forked the project, updated dependencies, updated the README, and published to Maven Central: https://github.com/outr/Hasher

**Comment by Nycto** [comment]
Apologies for letting this fall through the cracks. Dec and Jan are busy for me leading up to and falling out of the holidays. This has been pushed to Maven Central:

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.roundeights%22
