### ISSUE TITLE
RuntimeException: java.lang.NoClassDefFoundError: org/mindrot/jbcrypt/BCrypt

### ISSUE THREAD

**Issue by atyapin** [Nycto/Hasher#19]
There is an exception

> RuntimeException: java.lang.NoClassDefFoundError: org/mindrot/jbcrypt/BCrypt

when I try to run
```        
import com.roundeights.hasher.Implicits._

...

println("Salted BCrypt: " + hashMe.salt("sweet").bcrypt)
```
I fixed it by adding 
`libraryDependencies += "org.mindrot" % "jbcrypt" % "0.4"`
in build.sbt

**Comment by Nycto** [comment]
This is intentional and documented in the README: https://github.com/Nycto/Hasher#bcrypt

Not everyone is using this lib for bcrypt, so adding a dependency they don't need is wasteful
